### PR TITLE
The solution file, HelloWorld.ps1, is not supposed to exist. 

### PR DESCRIPTION
**Pull request by sophware**
HelloWorld.ps1 should be created by the user and, if it exists in advance, will cause the wrong output from tests (Invoke-Pester), as well as otherwise not match the instructions.

This commit removes the solution file.

NOTE:

When I run `exercism download --exercise=hello-world --track=powershell`, it doesn't actually download the repository we're collaborating on here.

### CODE REVIEW

**Comment by masters3d** [comment]
I think the instructions are outdated. What do you think of instead of making it more simple and get rid of all the instructions?

The `exercism` tool only downloads the exercise (skips he sample solution) and it gets deployed differently. 
I think you question should be added to the FAQ 
https://exercism.io/faqs
https://github.com/exercism/website-copy/blob/master/pages/faqs.md

**Comment by sophware** [comment]
I think I'm just doing this all an old way. There doesn't seem to be a new way, though. The new way to get started is assumedly this one:

https://exercism.io/getting-started

It links to this:

https://exercism.io/my/tracks

...which doesn't have PowerShell

The track does seem to exist, at this url:

https://exercism.io/my/tracks/powershell

If you go into the Hello World exercise, you are told to run this:

`exercism download --exercise=hello-world --track=powershell`

...which definitely puts HelloWorld.ps1 in the exercise directory, along with the test script and instructions, all of which contradict each other.

**Comment by masters3d** [comment]
You are not the only one
https://github.com/exercism/powershell/issues/36

It needs to be super simplified to be more of a check for people to make sure they have their environment working like suggested here:
https://github.com/exercism/exercism/issues/4707

The track still needs a couple of more exercises to launch. 
https://github.com/exercism/powershell/issues/58
https://github.com/exercism/powershell/issues/4

This track needs a lot of love. :)

**Comment by sophware** [comment]
Making it simple sounds great. What I'm suggesting is actually supportive of that, rather than in opposition. In fact, all that would have to be done to match issue 4707 is to remove the file I'm suggesting and then either remove the GETTING_STARTED file or replace its contents with the same simplified instructions already up on the web page for the exercise.

The work is practically done. It solves the confusion I'm hitting while perfectly matching the plan in issue 4707.

It's so simple, I must be missing something. One thing I know I'm missing is the knowledge of where the exercism binary pulls files from. Whatever that repository is has the same problems as this one, but slightly different copies of the files.

Either way, as-is, it conflicts with the suggestion in issue 4707 and it conflicts with itself.

Thanks for the responses. Looking forward to seeing the work progress on all the exercises here. It would be great to see the super simplification implemented on this particular exercise.

**Comment by masters3d** [comment]
PR for the documentation update.
https://github.com/exercism/powershell/pull/108

Do you want to make the `HelloWorld.ps1` file just be the below?

```
function Get-HelloWorld {
   return ""
}

```

**Comment by masters3d** [comment]
Then for test we will only need to have one test. 
```
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$sut = (Split-Path -Leaf $MyInvocation.MyCommand.Path) -replace '\.Tests\.', '.'
. "$here\$sut"

Describe "HelloWorldTest" {
	It "Outputs: 'Hello, World!'" {
		Get-HelloWorld | Should be 'Hello, World!'
	}
}
```

**Pull request closed without merging**
