### PR TITLE
added to getting started guide

### PR DESCRIPTION
**Pull request by KalebHawkins**
Added a link for installing Powershell (for non-windows users) and added step for installing Pester Module. New users to the language may feel discouraged when recieving
an error message saying the command was not found during their first test run.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Hi there! Did you close this on purpose?

**Comment by KalebHawkins** [comment]
No I didn't. Still getting used to GitHub stuff. I can reopen I think.

**Comment by ErikSchierboom** [comment]
@KalebHawkins It looks you've also deleted the `.gitignore` file. Could you revert that?

**Comment by KalebHawkins** [comment]
I added the .gitignore back - I don't know how that happened sorry about that. Everything should be set now..

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
