### PR TITLE
Adds leap lesson

### PR DESCRIPTION
**Pull request by spuder**
This is a really easy lesson since powershell has a native isleapyear function.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Sweet!

In most tracks we encourage people to do the math themselves, even if the language has native functionality. It provides a good starting point for talking about various types of complexity.

This is breaking on the configlet check (described here: https://github.com/exercism/exercism.io/blob/master/docs/reviewing-a-pull-request.md#consider-the-structural-requirements).

To fix it, add the slug to the `config.json` file.

**Comment by spuder** [comment]
fixed & squashed

**Comment by gyssels** [comment]
Adding the read me file by myself

**Comment by kytrinyx** [comment]
Please ensure that the build is green before merging. In this case it failed on the `configlet lint .` command. You can read more about configlet here: https://github.com/exercism/docs/blob/master/language-tracks/configuration/configlet.md

**Comment by kytrinyx** [comment]
Hm. Interesting -- this should have passed, since the readme is present.

That said, the README should be generated using the `configlet generate` command. I'll submit a PR.

**Comment by gyssels** [comment]
I actually added it manually. A PR is unnecessary.




______________________________________________________
Christian P. Gyssels

EUROPE  Land&Fax: +32 2 308 06 15 || BRAZIL  Cell Phone:+55 48 9695 5094  Land:+55 48 3037 2583  Fax:+55 11 2258 8526 || INTERNATIONAL Skype: cgyssels  E-mail:  • gyssels@dekeract.com<http://dekeract.com>

www.dekeract.com<http://www.dekeract.com>

Brazil | Belgium | Germany | France | United Kingdom

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments,is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail and destroy all copies of the original message.

________________________________

**Comment by kytrinyx** [comment]
It is necessary, as all the READMEs should be generated, so as to ensure consistency. That said—you already merged the PR.

**Comment by gyssels** [comment]
I mean actually "generated manually" and not automatically pulled from his code. but it is a generated version.

**Comment by kytrinyx** [comment]
Oh, cool! In that case we are all good!

**Pull request merged**
