### PR TITLE
Test exercism name convention

### PR DESCRIPTION
**Pull request by gyssels**
Test naming convention of exercism. Looking to see its accepts a non hello-word dashed name

Regards issue #49

### CODE REVIEW

**Comment by gyssels** [comment]
@kytrinyx  can you have a look to the issue #49?

**Comment by gyssels** [comment]
Did others renamings and refactoring. Sorry if now has a lot of noise in the examples ;)

**Comment by kytrinyx** [comment]
Yes, these filenames are all fine in terms of the website. The command line client will fetch whichever files are present, except anything with _example_ in the name (case insensitive, I believe).

Where possible, I'd prefer separate pull requests for separate exercises, as then these can be reviewed and merged separately.

**Comment by gyssels** [comment]
It was just a test to see cleanlier what should be done. the true PR will be done later.

**Comment by kytrinyx** [comment]
> It was just a test to see cleanlier what should be done.

perfect!

**Comment by gyssels** [comment]
>  @kytrinyx kytrinyx deleted the test-exercism-name-convention  branch 22 minutes ago

;) looked for during 5 minutes the "test-exercism-name-convention" to delete... ;) found it...
Thank you

**Comment by kytrinyx** [comment]
Oh no! I'm sorry—when I see a deletable branch I instinctively delete it...

**Pull request closed without merging**
