### PR TITLE
[New Exercise]: DnD Character

### PR DESCRIPTION
**Pull request by glaxxie**
Add DnD character exercise

### CODE REVIEW

**Review by meatball133 — COMMENTED** [review]
I think this looks good, although you have to fix that config.json ci.
I fixed the merge conflict for you, but if you like next time to solve it yourself so are you free to.

**Comment by glaxxie** [comment]
This should be ok now, that one typo really mess thing up around. Also thank you for fixing the merge conflict, next time if it happen in the config.json file just let me try to fix it.
I suppose I can just merge with whatever the current PR is so i can place the slug inside the config.json file at the right place to avoid merge conflict altogether?

**Review by meatball133 — APPROVED** [review]
Nice job!

**Comment by glaxxie** [comment]
This should be ok now, that one typo really mess thing up around. Also thank you for fixing the merge conflict, next time if it happen in the config.json file just let me try to fix it.
I suppose I can just merge with whatever the current PR is so i can place the slug inside the config.json file at the right place to avoid merge conflict altogether?

**Comment by meatball133** [comment]
I mean it mostly happens if 2 prs have changed the config.json at the same place, and I did a pr before you that did that. Other than that what I mostly try to do is to change config.json on different places all the time as long as I keep the difficulty rule true.

**Pull request merged**
