### PR TITLE
Run tests in Travis-CI

### LINKED ISSUE #103: Run tests in Travis
Windows support for Travis-CI is in beta release. It would be nice to get the tests running there.

https://docs.travis-ci.com/user/reference/windows/#powershell

### PR DESCRIPTION
**Pull request by cmccandless**
Resolves #103

### CODE REVIEW

**Comment by cmccandless** [comment]
@exercism/powershell This is ready for review.

I had to modify 2 exercises for Travis builds to pass:
- `two-fer`: This test suite had a different structure that other exercises I looked at. Something was causing an infinite recursive call, so I changed it to imitate the other exercises.
- `hamming`: The example solution was throwing a different error message than the tests were expecting.

If you would prefer that I make the above changes in separate pull requests, I can split those off as such.

**Comment by masters3d** [comment]
@cmccandless I don't see the windows matrix? Is that meant to be part of this change?

**Comment by cmccandless** [comment]
Travis-CI windows support is currently in beta (see links below).

It should still be possible to configure a windows build in the same `.travis.yml`, but for a first pass I wanted to get up and running with something I knew to be stable.

Sources:
- https://docs.travis-ci.com/user/reference/windows/
- https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by cmccandless** [comment]
@masters3d I've added a Windows build to the matrix, but I'm getting some error that doesn't make sense to me (my time away from Windows is starting to show). Can you take a look?

https://travis-ci.org/exercism/powershell/jobs/498861743

**Comment by masters3d** [comment]
Yeah, choco is the way to go https://github.com/pester/Pester/wiki/Installation-and-Update

**Comment by masters3d** [comment]
Why are you using bash to run the tests? I noticed that all the tests failed in the previous commit but the build passed, is there a way to make the build fail if there is any error in powershell?

**Comment by cmccandless** [comment]
> Why are you using bash to run the tests?

Git Bash is the shell used in Windows builds on Travis-CI. I could invoke a Powershell script and run everything that way, but I already had the working script that would set up the temporary directory and run the tests.

> I noticed that all the tests failed in the previous commit but the build passed, is there a way to make the build fail if there is any error in powershell?

I ran into this on the Linux side as well. Apparently, Powershell and Powershell-Core do **not** exit with a useful return code. So I'm filtering the console output for a fail count, and adding that up to check if everything passed. This should theoretically work in Git Bash as well, but it seems like there's some incompatibility there.

**Comment by cmccandless** [comment]
If someone wants to write a Powershell script for running the tests, that would be my preference (I'm a big fan of using a track's own language in its scripts). I simply lack the knowledge and time to write it myself.

Where we stand now with this PR, the unit tests are run in Powershell-Core on Linux. That is a large functional improvement over where things are now. If I could make a suggestion, we could:
1. Remove/comment out Windows build code from this PR
2. Merge with Linux builds only
3. Create an issue for Windows builds to be configured/scripted, letting someone with more Powershell knowledge complete that half of things

**Comment by masters3d** [comment]
This way better than not having it. Thank you so much

**Pull request merged**
