### PR TITLE
[Config.json]: Activate test-runnner

### PR DESCRIPTION
**Pull request by meatball133**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@meatball133 I'd like to first test things with the test runner enabled before setting it active. Maybe that can be a separate PR?

**Comment by meatball133** [comment]
Alright fixed but as I told you on discord, the test runner has some docker setup thing which I think Jermey has to do.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Yes, but that has been done :) See https://github.com/exercism/powershell-test-runner/actions/runs/5464951744 for a successful run

**Comment by ErikSchierboom** [comment]
Maybe you could make a post on the forum asking people to test the track a bit?

**Comment by meatball133** [comment]
https://forum.exercism.org/t/looking-for-people-to-test-the-powershell-track/6369

**Pull request merged**
