### PR TITLE
check for, install or update of Pester

### PR DESCRIPTION
**Pull request by axtens**
Installs Pester if not found. Updates otherwise.

### CODE REVIEW

**Comment by axtens** [comment]
```
 Line |
   2 |      Update-Module -Name Pester
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Module 'Pester' was not installed by using Install-Module, so it cannot be updated.
```
So that would imply that the Windows instance already has Pester installed. Would it be better then to have Pester installed in the Linux version the way it is in the Windows?

**Comment by ErikSchierboom** [comment]
I have no idea basically, as I don't really know much about PowerShell

**Comment by axtens** [comment]
In the short term, we can install if needed and it will never be needed in the Windows version because (I assume) the Dockerfile has specified to install it for Windows. In the long term, I'll see whether the Dockerfile can be told what to do for Linux.

**Comment by axtens** [comment]
Okay, passing all checks.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
