### PR TITLE
Improve the Hello World exercise

### LINKED ISSUE #36: Hello World exercise instructions are confusing and conflicting
Following the instructions for the Hello World exercise exactly does not guide the user accurately.  The tests still fail and there is some confusion around the naming of files.

### PR DESCRIPTION
**Pull request by kchenery**
This PR will fix #36 

The instructions for the exercise are improved to help guide a novice user through creating their first PowerShell script and function. 

Renamed the files to adher to Microsoft naming guidelines for PowerShell.

### CODE REVIEW

**Review by gyssels — CHANGES_REQUESTED** [review]
Please change to Get-verb...
Verb Out definition: Sends data out of the environment. For example, the Out-Printer cmdlet sends data to a printer. src: microsoft page: https://msdn.microsoft.com/en-us/library/ms714428%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

ps: config.json doen't need to be changed. And thank you for the good work...

**Comment by gyssels** [comment]
config.json doen't need to be changed. And thank you for the good work...

**Comment by gyssels** [comment]
Actually the files *.ps1 do not need to have the verb part of the command on it, if you think on "module" approach: more complicated problems will need several functions to solve, and we will submit altogether.

Actually waiting Owen (@kytrinyx) coming back from the name testing as specified on issue #49.

As the files on this PR cross several domains (as .\config\maintainers.json), I suggest doing different pull request.

I think we should "Close" this PR, but definitively want you to post back your contribution!

**Comment by kytrinyx** [comment]
> As the files on this PR cross several domains (as .\config\maintainers.json), I suggest doing different pull request.

Agreed!

> I think we should "Close" this PR, but definitively want you to post back your contribution!

We don't need to close the pull request—if @kchenery make a new branch with the changes that you want, @gyssels, then this branch can be force pushed up to the HEAD branch of this pull request, which will update the PR.

**Comment by gyssels** [comment]
> We don't need to close the pull request—if @kchenery make a new branch with the changes that you want, @gyssels, then this branch can be force pushed up to the HEAD branch of this pull request, which will update the PR.

I think it will be quicker to make a PR request from his branch, as I did for the Two-Fer implementation that came from him... It's very clear to see what he wants to commit

**Comment by kytrinyx** [comment]
> I think it will be quicker to make a PR request from his branch

That sounds good!

**Comment by kchenery** [comment]
Ive got a bit lost in what you actually want from me through the descriptions.  Can someone explain what you want changing in this PR and what you want in a new PR please?  I'll then make the necessary changes.

**Comment by kytrinyx** [comment]
> Actually waiting Owen (@kytrinyx) coming back from the name testing as specified on issue #49.

Shoot, I completely missed that you were waiting on me for something. Let me go see if I can sort that out now.

**Comment by kytrinyx** [comment]
Oh, nevermind. I see that I'm confused by the dates and that you're all sorted.

**Pull request closed without merging**
