### PR TITLE
[New Exercise]: Pig Latin

### PR DESCRIPTION
**Pull request by glaxxie**

### CODE REVIEW

**Comment by meatball133** [comment]
I have talked with Erik and if you would like, you could be assigned the maintainer of the powershell track. I, unfortunately, do not have the time to fully maintain this track since I work on 3 tracks excluding this one. I will still be around if you have any questions and I am here if you need to review anything specific. I think the track could become limited in the way that I don't have the time it deserves. The transition to maintainer can be linear (like if you want me to still maintain the test runner so is that an option). If you don't want to be maintainer that is also fine.

**Comment by glaxxie** [comment]
I've spent quite a lot of time contribute to the track so of course I'd like to continue doing it and making it better, however I have to make sure I'm capable of taking in more instead of making things worse. So if you don't mind explain a bit in details what are the duties of being maintainer, I would like to know more before making a decision.

**Comment by meatball133** [comment]
Well the "base" duties are mainly:

- Making sure things works as intended (ci does a lot for this), but it also includes making sure links are up to date and that the information stated in docs is up to date. 
- If there is some bug with the test runner is it mostly the maintainer duty to fix it or if some tests is broken etc
- Reveiwing prs and handling issues
- Making occasional updates to the language version used, this has to happen I think around 1-2 times every year.

Other duties, these are more optional:

- Developing new content, can be anything from tools, adding more features to the test runner, creating a syllabus, representer, analyzer, adding more practice exercises. As a maintainer the work more evolves around directing on how things should be done. Like how exercises should be setup (for example a functional approach or object-oriented), or select how the syllabus should be outlined etc, contributors have to follow how the maintainer wants it directed in most cases.
- Review prs on problem spec, this is highly optional, I very rarely do that but you are allowed to do it when being maintainer.

Some perks:

- Access to the maintainer channel on discord
- Access to post posts for the powershell track on the website.

**Comment by meatball133** [comment]
Also the exercism staff is on weekend until Tuesday so you have good amount of time to sleep on the matter. And if you have any more question feel free to ask

**Comment by glaxxie** [comment]
Ok, I've decided to accept the offer. It is a good opportunity for me to learn more and improving my skill.
And I still can ask for guidance and help if needed.
I probably gonna finally join the discord channel after this, I have an account but tend to avoid these things if I can, but it make more sense to communicate there than making nonstop posts on the forum.
For the short term future of this track, probably not much change, just keep adding exercise until next year and then moving on to other aspects.
One more question about the PR process if I to become maintainer: PR by myself still need another person to review before it could be merged just like before?

**Comment by meatball133** [comment]
You could select to not requiring reviews, but I would recommend pining either me or Erik to review your prs. Erik is off on weekends so if it is something on the weekend I am more likely to be able to review but on weekdays is Erik likely better.
I mean you will see how things feel and work out, and you will likely get a feel of what works and don't but take your time in the process. 

I don't know if you saw on the forum(https://forum.exercism.org/t/im-off-for-a-few-days/7611) but Erik and Jeremy is of, Erik is back on Thursday so I will ping him then, and tell him that you want to be maintainer. And if you don't feel like you want to be a maintainer at any point, you can always step aside.

**Comment by glaxxie** [comment]
Thank you, I have no more question for now. And yes I saw the post on the forum, it's no hurry.

**Comment by meatball133** [comment]
Alright, you have been added as a maintainer of the track, when you open a pr it should be a `reviewers` section to the right. You can select me and Erik, and we will both be pinged if you need something reviewed.

**Comment by glaxxie** [comment]
Sweet, thank you, I saw it now. I think we can finish with this PR now, I will join the discord in short. I've been busy the last couple days so I will start working on new exercise in the weekend.

**Review by meatball133 — APPROVED** [review]

**Pull request merged**
