### PR TITLE
Adding required docs

### LINKED ISSUE #18: Verify contents and format of track documentation
Each language track has documentation in the `docs/` directory, which gets included on the site
on each track-specific set of pages under [/languages](http://exercism.io/languages).

We've added some general guidelines about how we'd like the track to be documented in exercism/exercism.io#3315
which can be found at https://github.com/exercism/exercism.io/blob/master/docs/writing-track-documentation.md

Please take a moment to look through the documentation about documentation, and make sure that
the track is following these guidelines. Pay particularly close attention to **how to use images**
in the markdown files.

Lastly, if you find that the guidelines are confusing or missing important details, then a pull request
would be greatly appreciated.

### LINKED ISSUE #38: Missing ABOUT.md
When you browse to the [about PowerShell section on exercise.io](http://exercism.io/languages/powershell/about) the "complains" that `about.md` is missing.  We should add this file to describe the language.

### PR DESCRIPTION
**Pull request by kchenery**
Fixes #18 
Fixes #38 

Added the following /docs files:
* `ABOUT.md`
* `LEARNING.md`
* `INSTALLATION.md`
* `TESTS.md`
* `RESOURCES.md`

This PR will supersede PR #19

### CODE REVIEW

**Review by Tuxhedoh — CHANGES_REQUESTED** [review]
Line 3 of learning.md has a typo - This is the first repo I've worked on. Not sure if this is the best way to "fix" it.

**Comment by kchenery** [comment]
@Tuxhedoh thanks and good spotting.  You can actually comment against the code itself (would have helped here because I had to look through all files to find the typo 😃).  Just click on the line number next to the code to enter a comment about that line (or area) of code.

**Comment by kchenery** [comment]
Hmm...this build failed with a 443 to GitHub (not the changes themselves).  Dont have access to Travis CI to rerun.

Keen to get this merged if we can to get the documentation "going" at least :)

**Comment by gyssels** [comment]
Thank you! Great job!

**Pull request merged**
